<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>es.florida</groupId>
    <artifactId>AE03</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <build>
        <!-- <sourceDirectory>src</sourceDirectory> -->
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <!-- crear una aplicación standalone;  botón derecho sobre el proyecto Run as ➔ Maven install; cd C:\..\ejerciciosT3\target; java -jar .\ejerciciosT3-0.0.1-SNAPSHOT-shaded.jar -->
            <plugin>
            	<groupId>org.apache.maven.plugins</groupId> 
            	<artifactId>maven-shade-plugin</artifactId> 
            	<version>3.2.4</version> 
            	<executions> 
            		<execution>
            	 		<phase>package</phase> 
            	 		<goals>
            	  			<goal>shade</goal>
            	  		</goals>
            	  		<configuration>
	            	   		<transformers>
	            	    		<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer"> 
	            	   				<mainClass>es.florida.blackJack.Principal</mainClass>
	            	    		</transformer>
            	     		</transformers>
            	      	</configuration>
            		</execution>
            	</executions> 
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.mongodb/mongo-java-driver -->
		<dependency>
		    <groupId>org.mongodb</groupId>
		    <artifactId>mongo-java-driver</artifactId>
		    <version>3.12.14</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync -->
		<!--
		<dependency>
		    <groupId>org.mongodb</groupId>
		    <artifactId>mongodb-driver-sync</artifactId>
		    <version>5.3.0</version>
		</dependency>
		-->
        <!-- https://mvnrepository.com/artifact/org.json/json -->
		<dependency>
		    <groupId>org.json</groupId>
		    <artifactId>json</artifactId>
		    <version>20250107</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
		<dependency>
		    <groupId>commons-codec</groupId>
		    <artifactId>commons-codec</artifactId>
		    <version>1.17.2</version>
		</dependency>
    </dependencies>
</project>
